# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-28 15:26
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_mdb_c', models.CharField(max_length=5, verbose_name='Province code')),
                ('pr_code', models.FloatField()),
                ('pr_code_st', models.CharField(max_length=1)),
                ('pr_name', models.CharField(max_length=25)),
                ('albers_are', models.FloatField()),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=-1)),
            ],
        ),
    ]
